FROM php:8.2-fpm

# Installer les dépendances
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    curl \
    git \
    nano \
    libzip-dev \
    libpq-dev \
    libmcrypt-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev \
    libbz2-dev \
    libzstd-dev \
    liblzma-dev \
    libffi-dev \
    libargon2-dev \
    libxslt1-dev \
    libyaml-dev \
    libpq-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev \
    libbz2-dev \
    libzstd-dev \
    liblzma-dev \
    libffi-dev \
    libargon2-dev \
    libxslt1-dev \
    libyaml-dev \
    libpq-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev \
    libbz2-dev \
    libzstd-dev \
    liblzma-dev \
    libffi-dev \
    libargon2-dev \
    libxslt1-dev \
    libyaml-dev \
    libpq-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev \
    libbz2-dev \
    libzstd-dev \
    liblzma-dev \
    libffi-dev \
    libargon2-dev \
    libxslt1-dev \
    libyaml-dev \
    libpq-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev \
    libbz2-dev \
    libzstd-dev \
    liblzma-dev \
    libffi-dev \
    libargon2-dev \
    libxslt1-dev \
    libyaml-dev \
    libpq-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev \
    libbz2-dev \
    libzstd-dev \
    liblzma-dev \
    libffi-dev \
    libargon2-dev \
    libxslt1-dev \
    libyaml-dev \
    libpq-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev \
    libbz2-dev \
    libzstd-dev \
    liblzma-dev \
    libffi-dev \
    libargon2-dev \
    libxslt1-dev \
    libyaml-dev \
    libpq-dev \
    libsqlite3-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    libssl-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    libicu-dev \
    libxslt1-dev \
    libmagickwand-dev \
    libmagickcore-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libwebp-dev \
    libxpm-dev \
    libvpx-dev \
    libzip-dev \
    libmemcached-dev \
    libreadline-dev \
    libedit-dev \
    libsqlite3-dev \
    libtidy-dev \
    libaspell-dev \
    libpspell-dev \
    libsnmp-dev \
    libevent-dev \
    libgmp-dev \
    libssh2-1-dev
